# Generated by Django 2.2.8 on 2021-04-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام کتاب')),
                ('author_name', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('price', models.BigIntegerField(default=10000, verbose_name='قیمت')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200c\u200cها',
                'ordering': ('-created',),
            },
        ),
    ]
