# Generated by Django 2.2.8 on 2021-04-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novel', 'رمان'), ('scientific', 'علمی'), ('historical', 'تاریخی\u200c'), ('textbook', 'کتاب درسی')], default='novel', max_length=20),
        ),
    ]
